
from flask import Flask, jsonify
import pymongo
import os

app = Flask(__name__, static_folder='.', static_url_path='')


MONGO_HOST = os.getenv('MONGO_HOST','localhost')
MONGO_PORT = int(os.getenv('MONGO_PORT', 27017))

front_port = os.getenv('FRONTEND_PORT',8080)

def get_article_collection(host=MONGO_HOST,port=MONGO_PORT):
    client = pymongo.MongoClient(f"mongodb://{host}:{port}/")
    db = client["mydatabase"]
    return db["articles"]


collection = get_article_collection()

@app.route('/')
def home():
    # hands the HTML file when someone visits the root URL
    return app.send_static_file('index.html')

@app.route('/api/news')
def get_news():
    # _id is getting generated by ascending order, so the most recent ones have the greatest
    articles = list(collection.find({}, {'_id': 0}).sort('_id', -1).limit(20))
    # actually works fine:
    #return articles
    return jsonify(articles)

def main():
    app.run(host='0.0.0.0', port=front_port)


if __name__ == '__main__':
    main()
